menu:
  img: /u/base/logo.svg
  # title: Ecomare
  # sub: Ecología y Conservación Marina
  items:
  - label: Inicio
    url: /ecomare/
  - label: Noticias
    url: /ecomare/#noticias
  - label: Acerca del grupo
    url: /ecomare/grupo/
  - label: Proyectos
    url: /ecomare/proyectos/
  - label: Contratos
    url: /ecomare/contratos/
  - label: Publicaciones
    url: https://portalinvestigacion.um.es/grupos/31934/publicaciones
  - label: Tesis
    url: /ecomare/tesis/

footer:
  div: wavy-jump
  md: |
    [![Universidad de Murcia](/u/logo-um.svg)](/)

    ::place:: Avda. Teniente Flomesta, 5 · 30003 · Murcia

    - ::phone:: [+34 868 88 3000](tel:+34868883000) (Centralita)
    - ::phone:: [+34 868 88 8888](tel:+34868888888) (Información)
    {.list-inline}
