name: Deploy Hugo via SFTP

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Node (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'           # cache global por defecto

      - name: Install Node deps (root, si existe)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          fi

      - name: Install Node deps (tema sansoul, si existe)
        working-directory: themes/sansoul
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          fi

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.149.0'
          extended: true

      - name: Build
        run: sh do hugo

      - name: Deploy via SFTP (password)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          sftp_only: true
          local_path: './public/'
          remote_path: '/home/sp-dgroup/a1/www.um.es/ecomare'
          sftpArgs: '-o ConnectTimeout=10'
